import type { Metadata } from 'next';
import { ToastContainer, toast } from 'react-toastify';
import {
  Geist,
  Geist_Mono,
  Libre_Baskerville,
} from 'next/font/google';
import './globals.css';
import { getConfig } from '@/lib/config';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});
const libreBaskerville = Libre_Baskerville({
  variable: '--font-libre-baskerville',
  subsets: ['latin'],
  weight: ['400', '700'],
});
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { TOAST_POSITION } = getConfig();
  return (
    <html lang="en">
      <body
        className={`${libreBaskerville.className} antialiased dark`}
      >
        {children}
        <ToastContainer position={TOAST_POSITION} />
      </body>
    </html>
  );
}
